export default [
  {

    title: 'The first Header of checklist',
    items_data: [
      {
        item_title: 'Checklist1',
        description: 'Description for checklist oneee',
        tags: ['WHAT', 'CSS', 'jSoN'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist2',
        description: 'Ohh yeah dexcription 2',
        tags: ['HTML', 'TAG', 'TAG'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
      {
        item_title: 'Checklist 3',
        description: 'This is description 3',
        tags: ['ANGULAR', 'CSS', 'JSX'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 1,
      },
      {
        item_title: 'Checklist 4',
        description: 'This is dexcription 4',
        tags: ['HTmL', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist 5',
        description: 'This is dexcription 4',
        tags: ['JSON', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist 6',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 1,
      },
      {
        item_title: 'Checklist 7',
        description: 'This is something for 7',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
    ],
  },
  {
    title: '2-nd Header',
    items_data: [
      {
        item_title: 'Checklist1',
        description: 'BadabumBadabumBad',
        tags: ['WHAT', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist2',
        description: 'Ohh yeah dexcription 2',
        tags: ['HTML', 'TAG', 'TAG'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
      {
        item_title: 'Checklist3',
        description: 'This is description 3',
        tags: ['ANGULAR', 'CSS', 'JSX'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 1,
      },
      {
        item_title: 'Checklist4',
        description: 'This is dexcription 4',
        tags: ['HTmL', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist5',
        description: 'This is dexcription 4',
        tags: ['JSON', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 0,
      },
      {
        item_title: 'Checklist6',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 1,
      },
      {
        item_title: 'Checklist7',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
      {
        item_title: 'Checklist8',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
      {
        item_title: 'Checklist9',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
      {
        item_title: 'Checklist10',
        description: 'This is dexcription 4',
        tags: ['HTML', 'CSS'],
        details: '# Header 1 \n ## Header 2 \n ### Header 3 \n  * This block of Markdown contains [GitHub Flavored Markdown](https://github.github.com/gfm/)',
        priority: 2,
      },
    ],
  },
];
